name: Configure ccache and CFLAGS
description: Configure ccache and CFLAGS
runs:
  using: "composite"
  steps:
    - name: Install ccache, configure CFLAGS, update brew
      shell: bash
      run: |
        if [ "`uname`" = "Darwin" ]; then
          brew update
          brew install ccache
          brew upgrade
          echo CFLAGS=$CFLAGS -Wno-parentheses-equality -Wno-constant-logical-operand -stdlib=libc++ >> $GITHUB_ENV
          echo CXXFLAGS=$CXXFLAGS -Wno-parentheses-equality -Wno-constant-logical-operand -stdlib=libc++ >> $GITHUB_ENV
          echo CC=ccache /usr/bin/clang >> $GITHUB_ENV
          echo CXX=ccache /usr/bin/clang++ >> $GITHUB_ENV
          echo LDCXXSHARED=ccache /usr/bin/clang -bundle -undefined dynamic_lookup >> $GITHUB_ENV
          echo LDSHARED=ccache /usr/bin/clang -bundle -undefined dynamic_lookup >> $GITHUB_ENV
        else
          sudo apt-get install -y ccache libmemcached-dev
          echo CFLAGS=$CFLAGS -std=gnu++11 >> $GITHUB_ENV
          echo CXXFLAGS=$CXXCFLAGS -std=gnu++11 >> $GITHUB_ENV
        fi
